$ErrorActionPreference = "Stop"

# Configuration
$BuildDir = "build_release"
$DistDir = "dist"
$ExecutableName = "Huffman.exe"
$ZipName = "Huffman-Windows.zip"

# Clean previous build
if (Test-Path $BuildDir) {
    Remove-Item -Path $BuildDir -Recurse -Force
}
if (Test-Path $DistDir) {
    Remove-Item -Path $DistDir -Recurse -Force
}
if (Test-Path $ZipName) {
    Remove-Item -Path $ZipName -Force
}

# Configure CMake
Write-Host "Configuring CMake..."
cmake -B $BuildDir -DCMAKE_BUILD_TYPE=Release

# Build
Write-Host "Building project..."
cmake --build $BuildDir --config Release

# Prepare Dist folder
New-Item -ItemType Directory -Path $DistDir | Out-Null

# Copy Executable
Copy-Item "$BuildDir/$ExecutableName" -Destination $DistDir

# Copy Resources (if any exist in build dir)
if (Test-Path "$BuildDir/resource") {
    Copy-Item "$BuildDir/resource" -Destination $DistDir -Recurse
}

# Copy Qt Dependencies (generated by windeployqt in build dir)
# We copy all DLLs and specific folders that windeployqt usually creates
$QtFolders = @("iconengines", "imageformats", "platforms", "styles", "tls", "networkinformation")
foreach ($folder in $QtFolders) {
    if (Test-Path "$BuildDir/$folder") {
        Copy-Item "$BuildDir/$folder" -Destination "$DistDir/$folder" -Recurse
    }
}

# Copy all DLLs from build dir
Get-ChildItem -Path $BuildDir -Filter "*.dll" | Copy-Item -Destination $DistDir

# Create Zip
Write-Host "Creating Zip archive..."
Compress-Archive -Path "$DistDir/*" -DestinationPath $ZipName

Write-Host "Packaging complete: $ZipName"
