param (
    [string]$QtPath = ""
)

$ErrorActionPreference = "Stop"

# Get the project root directory (one level up from the script location)
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
if (-not $ScriptDir) { $ScriptDir = $PSScriptRoot }
$ProjectRoot = Split-Path -Parent $ScriptDir
Set-Location $ProjectRoot

Write-Host "Working in: $ProjectRoot"

# Configuration
$BuildDir = "build_release"
$DistDir = "dist"
$ExecutableName = "Huffman.exe"
$ZipName = "Huffman-Windows.zip"

# Clean previous build
if (Test-Path $BuildDir) {
    Remove-Item -Path $BuildDir -Recurse -Force
}
if (Test-Path $DistDir) {
    Remove-Item -Path $DistDir -Recurse -Force
}
if (Test-Path $ZipName) {
    Remove-Item -Path $ZipName -Force
}

# Configure CMake
Write-Host "Configuring CMake..."
$CMakeArgs = @("-B", $BuildDir, "-DCMAKE_BUILD_TYPE=Release")
if ($QtPath -ne "") {
    $CMakeArgs += "-DCMAKE_PREFIX_PATH=$QtPath"
    Write-Host "Using Qt Path: $QtPath"
}

cmake @CMakeArgs
if ($LASTEXITCODE -ne 0) {
    Write-Error "CMake configuration failed."
    exit $LASTEXITCODE
}

# Build
Write-Host "Building project..."
cmake --build $BuildDir --config Release
if ($LASTEXITCODE -ne 0) {
    Write-Error "Build failed."
    exit $LASTEXITCODE
}

# Determine source directory (handle Multi-Config generators like Visual Studio)
if (Test-Path "$BuildDir/Release/$ExecutableName") {
    $SourceDir = "$BuildDir/Release"
} else {
    $SourceDir = "$BuildDir"
}

Write-Host "Source Directory detected: $SourceDir"

# Prepare Dist folder
New-Item -ItemType Directory -Path $DistDir | Out-Null

# Copy Executable
Copy-Item "$SourceDir/$ExecutableName" -Destination $DistDir

# Copy Resources
# Check both SourceDir and BuildDir/resource because CMake file(COPY) puts it in CMAKE_BINARY_DIR
if (Test-Path "$SourceDir/resource") {
    Copy-Item "$SourceDir/resource" -Destination $DistDir -Recurse
} elseif (Test-Path "$BuildDir/resource") {
    Copy-Item "$BuildDir/resource" -Destination $DistDir -Recurse
}

# Copy Qt Dependencies (generated by windeployqt in source dir)
$QtFolders = @("iconengines", "imageformats", "platforms", "styles", "tls", "networkinformation", "generic")
foreach ($folder in $QtFolders) {
    if (Test-Path "$SourceDir/$folder") {
        Copy-Item "$SourceDir/$folder" -Destination "$DistDir/$folder" -Recurse
    }
}

# Copy all DLLs from source dir
Get-ChildItem -Path $SourceDir -Filter "*.dll" | Copy-Item -Destination $DistDir

# Create Zip
Write-Host "Creating Zip archive..."
Compress-Archive -Path "$DistDir/*" -DestinationPath $ZipName

Write-Host "Packaging complete: $ZipName"
