name: CI

on: push # when to trigger this. Here, on every push
jobs:
  build_and_test:
    name: "Build and test"
    strategy:
      matrix:
        os: [ubuntu-latest] # windows-latest commented out
    runs-on: ${{ matrix.os }} # use value from the matrix
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies (linux)
      run: sudo apt install ninja-build
      if: matrix.os == 'ubuntu-latest' # conditional, runs this step only on the Ubuntu runner

    # - name: Install Ninja (windows)
    #   if: matrix.os == 'windows-latest'
    #   run: |
    #     choco install ninja

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.2'
        dir: ${{ github.workspace }}
    - uses: ilammy/msvc-dev-cmd@v1 # This action essentially calls vcvarsall.bat for the latest VS in the runner for x64

    # Here we call CMake manually, there are solutions for that in the Marketplace: https://github.com/marketplace/actions/run-cmake
    - name: Configure CMake (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: cmake -S . -B build -G "Ninja Multi-Config"

    # - name: Configure CMake (Windows)
    #   if: matrix.os == 'windows-latest'
    #   run: cmake -S . -B build -G "Ninja Multi-Config"

    - name: Build
      run: cmake --build build --config Debug

    - name: Test
      env:
        QT_QPA_PLATFORM: offscreen
      run: ctest --test-dir build -C Debug --output-on-failure