name: Build and Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release Version (e.g. v1.0.0)'
        required: true
        default: 'v1.0.0'

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.8.0'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2022_64'
        
    - name: Package Windows
      shell: pwsh
      run: ./scripts/package_win.ps1
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Huffman-Windows
        path: Huffman-Windows.zip

  build-linux:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.8.0'
        host: 'linux'
        target: 'desktop'
        arch: 'linux_gcc_64'
        
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-dev libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0 x11-utils
        
    - name: Package Linux
      run: chmod +x scripts/package_linux.sh && ./scripts/package_linux.sh
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Huffman-Linux
        path: Huffman-Linux.tar.gz

  create-release:
    needs: [build-windows, build-linux]
    runs-on: ubuntu-latest
    steps:
    - name: Download Windows Artifact
      uses: actions/download-artifact@v4
      with:
        name: Huffman-Windows
        
    - name: Download Linux Artifact
      uses: actions/download-artifact@v4
      with:
        name: Huffman-Linux
        
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ inputs.version }}
        name: Release ${{ inputs.version }}
        draft: false
        prerelease: false
        files: |
          Huffman-Windows.zip
          Huffman-Linux.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
